# Generated by Django 4.2.2 on 2024-08-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_next_send_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('name',), 'permissions': [('view_mailings', 'Can view mailings'), ('cancel_mailings', 'Can cancel mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
